name: daleel_child
description: معلمي (دليل الطفل سابقًا) - منصة تعليمية عربية وإنجليزية للأطفال من الروضة حتى الصف الثالث.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_tts: ^4.2.5
  audioplayers: ^6.1.0
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  google_mlkit_digital_ink_recognition: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/child_avatars/
    - assets/images/games/
    - assets/images/store/
    - assets/audio/
    - assets/data/
